FROM bitnami/php-fpm:7.4-prod
LABEL maintainer="奶爸 <hi@nai.ba>"

RUN install_packages cron

# Please bind crontab file to /etc/cron.d/crontab-config

CMD chmod 0755 /etc/cron.d/crontab-config && \
    crontab /etc/cron.d/crontab-config && cron f && \
    sleep infinity