FROM alpine
LABEL maintainer="奶爸 <hi@nai.ba>"

# Get version on https://pkgs.alpinelinux.org/package/edge/community/x86/beanstalkd
ENV Version=1.11-r0

RUN apk add --no-cache beanstalkd=${Version}

WORK /data

EXPOSE 11300
ENTRYPOINT ["/usr/bin/beanstalkd","-b","/data"]
