name: beanstalkd

on: 
  push:
    paths:
      - 'Dockerfile.beanstalkd'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker push
        env:
          DockerPassword: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t docker.pkg.github.com/naiba/Dockerfiles/beanstalkd -f ./Dockerfile.beanstalkd
          docker login -u naiba -p $DockerPassword docker.pkg.github.com
          docker push docker.pkg.github.com/naiba/Dockerfiles/beanstalkd
