name: php-cron

on:
  push:
    paths:
      - "Dockerfile.php-cron"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker push
        env:
          DockerPassword: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          docker login -u naiba -p $DockerPassword docker.pkg.github.com
          docker build -t docker.pkg.github.com/naiba/dockerfiles/php-cron -f Dockerfile.php-cron .
          docker push docker.pkg.github.com/naiba/dockerfiles/php-cron
