name: php-cron-ioncube

on:
  push:
    paths:
      - "Dockerfile.php-cron-ioncube"
      - "Dockerfile.php-fpm-ioncube"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/php-fpm-ioncube -f Dockerfile.php-fpm-ioncube .
          docker build -t ghcr.io/${{ github.repository_owner }}/php-cron-ioncube -f Dockerfile.php-cron-ioncube .
          docker push ghcr.io/${{ github.repository_owner }}/php-cron-ioncube
