name: php-fpm

on:
  push:
    paths:
      - "Dockerfile.php-fpm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/php-fpm -f Dockerfile.php-fpm .
          docker push ghcr.io/${{ github.repository_owner }}/php-fpm
