name: php

on:
  push:
    paths:
      - "Dockerfile.php"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/php -f Dockerfile.php .
          docker push ghcr.io/${{ github.repository_owner }}/php
