name: php8-fpm

on:
  push:
    paths:
      - "Dockerfile.php8-fpm"
      - ".github/workflows/php-fpm.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log in to the GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.php8-fpm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/php-fpm
            ghcr.io/${{ github.repository_owner }}/php-fpm:8
